var data = [ {
	"acceptedNum" : "57",
	"acceptedRate" : " 100.00%",
	"applynum" : "57",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "1",
	"invalidNum" : "0",
	"jumpNum" : "3",
	"overtimeNum" : "0",
	"passedNum" : "51",
	"passedRate" : "  89.47%",
	"problemInstanceNum" : "10",
	"problemNum" : "17",
	"problemRate" : "  17.54%",
	"refusedNum" : "0",
	"short_name" : "市发改委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "7",
	"timeoutbNum" : "7",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "1",
	"warningRate" : "   1.75%"
}, {
	"acceptedNum" : "27",
	"acceptedRate" : " 100.00%",
	"applynum" : "27",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "2",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "18",
	"passedRate" : "  66.67%",
	"problemInstanceNum" : "1",
	"problemNum" : "2",
	"problemRate" : "   3.70%",
	"refusedNum" : "0",
	"short_name" : "市教委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "1",
	"timeoutbNum" : "1",
	"timeoutcNum" : "0",
	"vetoNum" : "3",
	"warningNUM" : "1",
	"warningRate" : "   3.70%"
}, {
	"acceptedNum" : "25",
	"acceptedRate" : " 100.00%",
	"applynum" : "25",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "2",
	"govid" : "3",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "24",
	"passedRate" : "  96.00%",
	"problemInstanceNum" : "1",
	"problemNum" : "2",
	"problemRate" : "   4.00%",
	"refusedNum" : "0",
	"short_name" : "市科委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "90",
	"acceptedRate" : " 100.00%",
	"applynum" : "90",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "29",
	"invalidNum" : "0",
	"jumpNum" : "2",
	"overtimeNum" : "0",
	"passedNum" : "90",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "2",
	"problemNum" : "2",
	"problemRate" : "   2.22%",
	"refusedNum" : "0",
	"short_name" : "市经信委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "4",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市民委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "43",
	"acceptedRate" : " 100.00%",
	"applynum" : "43",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "8",
	"govid" : "5",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "43",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "5",
	"problemNum" : "8",
	"problemRate" : "  11.63%",
	"refusedNum" : "0",
	"short_name" : "市公安局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "122",
	"acceptedRate" : "  68.16%",
	"applynum" : "179",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "7",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "121",
	"passedRate" : "  99.18%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市民政局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "220",
	"acceptedRate" : " 100.00%",
	"applynum" : "220",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "8",
	"invalidNum" : "0",
	"jumpNum" : "3",
	"overtimeNum" : "0",
	"passedNum" : "216",
	"passedRate" : "  98.18%",
	"problemInstanceNum" : "3",
	"problemNum" : "3",
	"problemRate" : "   1.36%",
	"refusedNum" : "0",
	"short_name" : "市司法局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "4",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "430",
	"acceptedRate" : " 100.00%",
	"applynum" : "430",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "38",
	"govid" : "9",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "430",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "33",
	"problemNum" : "38",
	"problemRate" : "   7.67%",
	"refusedNum" : "0",
	"short_name" : "市财政局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "1496",
	"acceptedRate" : "  96.33%",
	"applynum" : "1553",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "10",
	"invalidNum" : "0",
	"jumpNum" : "3",
	"overtimeNum" : "0",
	"passedNum" : "1491",
	"passedRate" : "  99.67%",
	"problemInstanceNum" : "8",
	"problemNum" : "13",
	"problemRate" : "   0.53%",
	"refusedNum" : "4",
	"short_name" : "市人力社保局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "5",
	"timeoutbNum" : "5",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "4",
	"warningRate" : "   0.27%"
}, {
	"acceptedNum" : "124",
	"acceptedRate" : "  77.99%",
	"applynum" : "159",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "12",
	"invalidNum" : "0",
	"jumpNum" : "6",
	"overtimeNum" : "0",
	"passedNum" : "97",
	"passedRate" : "  78.23%",
	"problemInstanceNum" : "37",
	"problemNum" : "68",
	"problemRate" : "  29.84%",
	"refusedNum" : "0",
	"short_name" : "市国土局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "31",
	"timeoutbNum" : "31",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "23",
	"warningRate" : "  18.55%"
}, {
	"acceptedNum" : "857",
	"acceptedRate" : "  96.08%",
	"applynum" : "892",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "1",
	"govid" : "27",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "495",
	"passedRate" : "  57.76%",
	"problemInstanceNum" : "5",
	"problemNum" : "9",
	"problemRate" : "   0.58%",
	"refusedNum" : "21",
	"short_name" : "市环保局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "4",
	"timeoutbNum" : "4",
	"timeoutcNum" : "0",
	"vetoNum" : "37",
	"warningNUM" : "1",
	"warningRate" : "   0.12%"
}, {
	"acceptedNum" : "134",
	"acceptedRate" : "  47.86%",
	"applynum" : "280",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "13",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "114",
	"passedRate" : "  85.07%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市规划委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "20",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "2650",
	"acceptedRate" : "  73.02%",
	"applynum" : "3629",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "209",
	"govid" : "14",
	"invalidNum" : "0",
	"jumpNum" : "489",
	"overtimeNum" : "0",
	"passedNum" : "2309",
	"passedRate" : "  87.13%",
	"problemInstanceNum" : "479",
	"problemNum" : "798",
	"problemRate" : "  18.08%",
	"refusedNum" : "8",
	"short_name" : "市住建委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "37",
	"timeoutbNum" : "60",
	"timeoutcNum" : "3",
	"vetoNum" : "297",
	"warningNUM" : "29",
	"warningRate" : "   1.09%"
}, {
	"acceptedNum" : "26",
	"acceptedRate" : " 100.00%",
	"applynum" : "26",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "53",
	"govid" : "15",
	"invalidNum" : "0",
	"jumpNum" : "3",
	"overtimeNum" : "0",
	"passedNum" : "18",
	"passedRate" : "  69.23%",
	"problemInstanceNum" : "21",
	"problemNum" : "57",
	"problemRate" : "  80.77%",
	"refusedNum" : "0",
	"short_name" : "市市政市容委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "1",
	"timeoutcNum" : "0",
	"vetoNum" : "7",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "1182",
	"acceptedRate" : "  99.83%",
	"applynum" : "1184",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "21",
	"govid" : "16",
	"invalidNum" : "0",
	"jumpNum" : "56",
	"overtimeNum" : "0",
	"passedNum" : "1067",
	"passedRate" : "  90.27%",
	"problemInstanceNum" : "70",
	"problemNum" : "85",
	"problemRate" : "   5.92%",
	"refusedNum" : "1",
	"short_name" : "市交通委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "4",
	"timeoutbNum" : "4",
	"timeoutcNum" : "0",
	"vetoNum" : "114",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "471",
	"acceptedRate" : "  99.16%",
	"applynum" : "475",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "28",
	"invalidNum" : "1",
	"jumpNum" : "3",
	"overtimeNum" : "0",
	"passedNum" : "423",
	"passedRate" : "  89.81%",
	"problemInstanceNum" : "3",
	"problemNum" : "3",
	"problemRate" : "   0.64%",
	"refusedNum" : "2",
	"short_name" : "市水务局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "47",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "17682",
	"acceptedRate" : "  86.38%",
	"applynum" : "20471",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "18",
	"invalidNum" : "1",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "15264",
	"passedRate" : "  86.33%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "56",
	"short_name" : "市商务委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "2011",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "174",
	"acceptedRate" : "  95.60%",
	"applynum" : "182",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "19",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "168",
	"passedRate" : "  96.55%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "6",
	"short_name" : "市文化局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "2703",
	"acceptedRate" : "  95.82%",
	"applynum" : "2821",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "1",
	"govid" : "20",
	"invalidNum" : "0",
	"jumpNum" : "75",
	"overtimeNum" : "0",
	"passedNum" : "2551",
	"passedRate" : "  94.38%",
	"problemInstanceNum" : "89",
	"problemNum" : "102",
	"problemRate" : "   3.29%",
	"refusedNum" : "0",
	"short_name" : "市卫生局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "13",
	"timeoutbNum" : "13",
	"timeoutcNum" : "0",
	"vetoNum" : "137",
	"warningNUM" : "13",
	"warningRate" : "   0.48%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "21",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市人口计生委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "2226",
	"acceptedRate" : " 100.00%",
	"applynum" : "2226",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "39",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "2226",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市旅游委",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "12",
	"acceptedRate" : " 100.00%",
	"applynum" : "12",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "24",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "12",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市地税局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "1534",
	"acceptedRate" : " 100.00%",
	"applynum" : "1534",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "25",
	"invalidNum" : "0",
	"jumpNum" : "4",
	"overtimeNum" : "0",
	"passedNum" : "1530",
	"passedRate" : "  99.74%",
	"problemInstanceNum" : "7",
	"problemNum" : "10",
	"problemRate" : "   0.46%",
	"refusedNum" : "0",
	"short_name" : "市工商局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "3",
	"timeoutbNum" : "3",
	"timeoutcNum" : "0",
	"vetoNum" : "1",
	"warningNUM" : "3",
	"warningRate" : "   0.20%"
}, {
	"acceptedNum" : "259",
	"acceptedRate" : " 100.00%",
	"applynum" : "259",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "26",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "221",
	"passedRate" : "  85.33%",
	"problemInstanceNum" : "32",
	"problemNum" : "64",
	"problemRate" : "  12.36%",
	"refusedNum" : "0",
	"short_name" : "市质监局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "32",
	"timeoutbNum" : "32",
	"timeoutcNum" : "0",
	"vetoNum" : "2",
	"warningNUM" : "12",
	"warningRate" : "   4.63%"
}, {
	"acceptedNum" : "1",
	"acceptedRate" : " 100.00%",
	"applynum" : "1",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "38",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "1",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市安监局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "278",
	"acceptedRate" : " 100.00%",
	"applynum" : "278",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "31",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "257",
	"passedRate" : "  92.45%",
	"problemInstanceNum" : "1",
	"problemNum" : "2",
	"problemRate" : "   0.36%",
	"refusedNum" : "0",
	"short_name" : "市广电局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "1",
	"timeoutbNum" : "1",
	"timeoutcNum" : "0",
	"vetoNum" : "16",
	"warningNUM" : "1",
	"warningRate" : "   0.36%"
}, {
	"acceptedNum" : "9955",
	"acceptedRate" : "  99.97%",
	"applynum" : "9958",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "32",
	"invalidNum" : "0",
	"jumpNum" : "4",
	"overtimeNum" : "0",
	"passedNum" : "9949",
	"passedRate" : "  99.94%",
	"problemInstanceNum" : "5",
	"problemNum" : "6",
	"problemRate" : "   0.05%",
	"refusedNum" : "0",
	"short_name" : "市新闻出版局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "1",
	"timeoutbNum" : "1",
	"timeoutcNum" : "0",
	"vetoNum" : "5",
	"warningNUM" : "1",
	"warningRate" : "   0.01%"
}, {
	"acceptedNum" : "48",
	"acceptedRate" : "  72.73%",
	"applynum" : "66",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "33",
	"invalidNum" : "0",
	"jumpNum" : "4",
	"overtimeNum" : "0",
	"passedNum" : "47",
	"passedRate" : "  97.92%",
	"problemInstanceNum" : "5",
	"problemNum" : "6",
	"problemRate" : "  10.42%",
	"refusedNum" : "18",
	"short_name" : "市文物局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "1",
	"timeoutbNum" : "1",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "1",
	"warningRate" : "   2.08%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "34",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市体育局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "8784",
	"acceptedRate" : "  99.87%",
	"applynum" : "8795",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "35",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "8782",
	"passedRate" : "  99.98%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "6",
	"short_name" : "市统计局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "   0.00%",
	"applynum" : "1",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "44",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "   0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市园林绿化局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "   0.00%",
	"applynum" : "1",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "47",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "   0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市知识产权局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "240",
	"acceptedRate" : "  99.59%",
	"applynum" : "241",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "51",
	"invalidNum" : "0",
	"jumpNum" : "20",
	"overtimeNum" : "0",
	"passedNum" : "222",
	"passedRate" : "  92.50%",
	"problemInstanceNum" : "16",
	"problemNum" : "20",
	"problemRate" : "   6.67%",
	"refusedNum" : "0",
	"short_name" : "市民防局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "18",
	"warningNUM" : "1",
	"warningRate" : "   0.42%"
}, {
	"acceptedNum" : "883",
	"acceptedRate" : " 100.00%",
	"applynum" : "883",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "49",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "883",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "   0.00%",
	"refusedNum" : "0",
	"short_name" : "市编办",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "46",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市档案局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "557",
	"acceptedRate" : "  97.38%",
	"applynum" : "572",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "30",
	"invalidNum" : "0",
	"jumpNum" : "32",
	"overtimeNum" : "0",
	"passedNum" : "553",
	"passedRate" : "  99.28%",
	"problemInstanceNum" : "33",
	"problemNum" : "33",
	"problemRate" : "   5.92%",
	"refusedNum" : "0",
	"short_name" : "市农业局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "1",
	"timeoutcNum" : "0",
	"vetoNum" : "3",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "54",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市粮食局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "1037",
	"acceptedRate" : "  99.23%",
	"applynum" : "1045",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "1",
	"govid" : "37",
	"invalidNum" : "0",
	"jumpNum" : "1",
	"overtimeNum" : "0",
	"passedNum" : "875",
	"passedRate" : "  84.38%",
	"problemInstanceNum" : "4",
	"problemNum" : "5",
	"problemRate" : "   0.39%",
	"refusedNum" : "0",
	"short_name" : "市药监局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "1",
	"timeoutbNum" : "2",
	"timeoutcNum" : "0",
	"vetoNum" : "160",
	"warningNUM" : "2",
	"warningRate" : "   0.19%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "70",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市中医管理局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "52",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市邮政管理局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "55",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市通信管理局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "15",
	"acceptedRate" : " 100.00%",
	"applynum" : "15",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "2",
	"govid" : "50",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "15",
	"passedRate" : " 100.00%",
	"problemInstanceNum" : "2",
	"problemNum" : "2",
	"problemRate" : "  13.33%",
	"refusedNum" : "0",
	"short_name" : "市地震局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "   0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "56",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市烟草专卖局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
}, {
	"acceptedNum" : "0",
	"acceptedRate" : "0.00%",
	"applynum" : "0",
	"clazz" : "cn.com.pansky.fgwwsjc.orm.model.UnitStatistical",
	"exceedNum" : "0",
	"govid" : "57",
	"invalidNum" : "0",
	"jumpNum" : "0",
	"overtimeNum" : "0",
	"passedNum" : "0",
	"passedRate" : "0.00%",
	"problemInstanceNum" : "0",
	"problemNum" : "0",
	"problemRate" : "0.00%",
	"refusedNum" : "0",
	"short_name" : "市气象局",
	"stoppedNum" : "0",
	"telloutNum" : "0",
	"timeoutaNum" : "0",
	"timeoutbNum" : "0",
	"timeoutcNum" : "0",
	"vetoNum" : "0",
	"warningNUM" : "0",
	"warningRate" : "0.00%"
} ];
